version: 2.1

workflows:
  pipeline:
    jobs:
      - build-test-lint
      - containerization:
          context:
            - Docker_hub
            - heroku
          requires:
            - build-test-lint
          filters:
            branches:
              only: master
      - deploy:
          context:
            - Docker_hub
            - heroku
          requires:
            - containerization
          filters:
            branches:
              only: master

orbs:
  python: circleci/python@1.5.0

jobs:
  build-test-lint: 
    docker:
      - image: python:3.8-alpine
    steps:
      - checkout
      # - restore_cache:
      #     key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - run:
          name: Running linting
          command: |
            . venv/bin/activate
            flake8 --format=html --htmldir=flake-report
      - store_artifacts:
          path: flake-report/
          destination: flake-report
  containerization:
    docker:
      - image: python:3.8-alpine
    steps:
      - checkout
      - setup_remote_docker
      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            apk add curl
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image.
      - run:
          name: Package app and push to DockerHub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1

  deploy:
    machine: True
    steps:
      - checkout
      - run:
          name: Installing Heroku CLI
          command: |
            set -e
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku create $HEROKU_APP_NAME --region eu || true
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set SECRET_KEY=$DJANGO_SECRET_KEY -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set DEBUG=$DEBUG -a $HEROKU_APP_NAME
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku config:set SENTRY_DSN=$SENTRY_DSN -a $HEROKU_APP_NAME

      - run:
          name: Pulling container from Dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker pull $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
      
      - run:
          name: Pushing container to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            docker tag $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      
      - run:
          name: Releasing container
          command: |          
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web -a $HEROKU_APP_NAME
